In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/dirty_cafe_sales.csv')

In [ ]:
# --------
#CONVERSION OF QUANTITY COLUMN FROM OBJECT TO NUMERIC
# --------

df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'], errors='coerce')
df['total_spent'] = pd.to_numeric(df['total_spent'], errors='coerce')

In [ ]:
# --------
# CONVERSION OF TRANSACTION DATE COLUMN
# --------

df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce',format = 'mixed')

In [ ]:
# -------
# CHECKING FOR DUPLICATE ROWS
# -------

df.duplicated().value_counts()

In [15]:
# ------
# CLEANING COLUMN NAMES
# ------

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [17]:
# ------
# STANDARDIZE COLUMN TEXT VALUES i.e trailing spaces and conversion to lower case
# -------

df['item'] = df['item'].str.strip().str.lower()
df['location'] = df['location'].str.strip().str.lower()
df['payment_method'] = df['payment_method'].str.strip().str.lower()

In [102]:
# ------
# HANDLING MISSING VALUES IN THE PRICE_PER_UNIT COLUMN
# ------

# Assign 1.0 to 'price_per_unit' for all 'cookie' items
df.loc[df['item'] == 'cookie', 'price_per_unit'] = 1.0

# Assign 1.5 to 'price_per_unit' for all 'tea' items
df.loc[df['item'] == 'tea', 'price_per_unit'] = 1.5

# Assign 2.0 to 'price_per_unit' for all 'coffee' items
df.loc[df['item'] == 'coffee', 'price_per_unit'] = 2.0

# Assign 3.0 to 'price_per_unit' for all 'cake' and 'juice' items
df.loc[df['item'].isin(['cake', 'juice']), 'price_per_unit'] = 3.0

# Assign 4.0 to 'price_per_unit' for all 'sandwich' and 'smoothie' items
df.loc[df['item'].isin(['sandwich','smoothie']), 'price_per_unit'] = 4.0

# Assign 5.0 to 'price_per_unit' for all 'salad' items
df.loc[df['item'] == 'salad', 'price_per_unit'] = 5.0

# Display a sample of the updated DataFrame to verify
display(df[df['item'] == 'sandwich'].head())

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
7,TXN_6699534,sandwich,4.0,4.0,16.0,cash,unknown,2023-10-28 00:00:00
9,TXN_2064365,sandwich,5.0,4.0,20.0,unknown,in-store,2023-12-31 00:00:00
11,TXN_3051279,sandwich,2.0,4.0,8.0,credit card,takeaway,unknown
12,TXN_7619095,sandwich,2.0,4.0,8.0,cash,in-store,2023-05-03 00:00:00
16,TXN_3765707,sandwich,1.0,4.0,4.0,unknown,unknown,2023-06-10 00:00:00

In [62]:
# ------
# HANDLING MISSING VALUES IN THE QUANTITY COLUMN. THIS WILL BE DONE BY DIVIDING THE TOTAL SPENT BY THE PRICE PER UNIT
# ------

df.loc[
    (df['quantity'].isna()) &
    (df['price_per_unit'].notna())&
    (df['total_spent'].notna()), 'quantity'
] = df['total_spent']/df['price_per_unit']

In [63]:
# ------
# HANDLING MISSING VALUES IN THE TOTAL SPENT COLUMN. THIS WILL BE DONE BY MULTIPLYING THE QUANTITY BY THE PRICE PER UNIT
# ------

df.loc[
    (df['total_spent'].isna())&
    (df['price_per_unit'].notna())&
    (df['quantity'].notna()), 'total_spent'
] = df['quantity']*df['price_per_unit']

In [67]:
# ------
# HANDLING MISSING VALUES IN THE PRICE_PER_UNIT COLUMN. THIS WILL BE DONE BY DIVIDING THE TOTAL SPENT BY THE QUANTITY
# ------

df.loc[
    (df['price_per_unit']).isna()&
    (df['total_spent'].notna())&
    (df['quantity'].notna()), 'price_per_unit'
] = df['total_spent']/df['quantity']

In [68]:
df.tail()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
9995,TXN_7672686,coffee,2.0,2.0,4.0,NaN,unknown,2023-08-30
9996,TXN_9659401,NaN,3.0,1.0,3.0,digital wallet,NaN,2023-06-02
9997,TXN_5255387,coffee,4.0,2.0,8.0,digital wallet,NaN,2023-03-02
9998,TXN_7695629,cookie,3.0,1.0,3.0,digital wallet,NaN,2023-12-02
9999,TXN_6170729,sandwich,3.0,4.0,12.0,cash,in-store,2023-11-07

In [69]:
# ------
# HANDLING MISSING VALUES IN THE PRICE_PER_UNIT COLUMN
# ------

# Assign 1.0 to 'price_per_unit' for all 'cookie' items
df.loc[df['item'] == 'cookie', 'price_per_unit'] = 1.0

# Assign 1.5 to 'price_per_unit' for all 'tea' items
df.loc[df['item'] == 'tea', 'price_per_unit'] = 1.5

# Assign 2.0 to 'price_per_unit' for all 'coffee' items
df.loc[df['item'] == 'coffee', 'price_per_unit'] = 2.0

# Assign 3.0 to 'price_per_unit' for all 'cake' and 'juice' items
df.loc[df['item'].isin(['cake', 'juice']), 'price_per_unit'] = 3.0

# Assign 4.0 to 'price_per_unit' for all 'sandwich' and 'smoothie' items
df.loc[df['item'].isin(['sandwich','smoothie']), 'price_per_unit'] = 4.0

# Assign 5.0 to 'price_per_unit' for all 'salad' items
df.loc[df['item'] == 'salad', 'price_per_unit'] = 5.0

In [89]:
# ------
# HANDLING MISSING VALUES IN THE ITEM COLUMN
# ------

df.loc[df['price_per_unit'] == 1.0, 'item'] = 'cookie'
df.loc[df['price_per_unit'] == 1.5, 'item'] = 'tea'
df.loc[df['price_per_unit'] == 2.0, 'item'] = 'coffee'
df.loc[df['price_per_unit'] == 5.0, 'item'] = 'salad'

In [ ]:
missing_items_df = df[df['item'].isnull()]
display(missing_items_df)

In [99]:
# -------
# HANDLING NAN AND ERROR VALUES
# -------


df = df.replace(np.nan, 'unknown')
df = df.replace('error', 'unknown')

Empty DataFrame
Columns: [transaction_id, item, quantity, price_per_unit, total_spent, payment_method, location, transaction_date]
Index: []

In [ ]:
output_path = '/content/drive/MyDrive/cleaned_cafe_sales.csv'
df.to_csv(output_path, index=False)
print(f"DataFrame saved to: {output_path}")

# Display the first few rows of the saved CSV to confirm
cleaned_df = pd.read_csv(output_path)
display(cleaned_df.head())